
services:
  app:
    build: ./app
    container_name: langchain-ollama
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:0.13.1-rc0
    container_name: ollama
    restart: always
    ports:
      - "11440:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: