networks:
  agent_network:
    driver: bridge

services:
  app:
    build: ./app
    container_name: langchain-ollama
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - ollama
      - agent_mongodb_db
    networks:
      - agent_network

  ollama:
    image: ollama/ollama:0.20.7
    container_name: ollama
    restart: always
    ports:
      - "11445:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - agent_network

  agent_mongodb_db:
    image: mongodb/mongodb-atlas-local:8.0.6
    container_name: agent_mongodb_container
    hostname: agent_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot
    networks:
      - agent_network

  frontend_streamlit:
    build: ./streamlit_app
    container_name: intelligent_agent_dashboard
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
      - streamlit_data_v1:/app/data
    depends_on:
      - app
      - agent_mongodb_db
    networks:
      - agent_network

volumes:
  ollama_data:
  db:
  configdb:
  mongot:
  streamlit_data_v1: